repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-json
    -   id: check-added-large-files # Vérifie qu'on n'a pas oublié LFS pour un nouveau gros fichier

-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black-jupyter # Reformate proprement le code Python dans les notebooks

-   repo: https://github.com/kynan/nbstripout
    rev: 0.6.1
    hooks:
    -   id: nbstripout # Vide automatiquement les outputs (images/logs) avant le commit
